### ISSUE TITLE
Add a Dependabot remediation

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#1078]
Raise a PR along the lines of what Mediator has currently:

```
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "tools"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "docs"
    schedule:
      interval: "daily"
```

This would probably require a specialized remediator that would look at the contents of the git repository, scan for ecosystems and set up the dependabot config appropriately. If short on time, we can start with configuring the main ecosystem (typically based on what’s in the root of the repo). Maybe we could save the ecosystems in the git ingestor?
