### ISSUE TITLE
Incorrect profile evaluation when using multiples rules of the same rule type

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#1609]
**Describe the bug**

Evaluation is not correct when there are multiple rules in a single profile for the same rule type, i.e. 2 `dependabot_configured` rules.

This results to having:
* a single rule evaluation entry whereas there should be one for each rule type
* the resulting rule eval status is based on the last evaluated rule of this type

**To Reproduce**

1. Create a profile with more than 1 rule type entries
2. List the profile details

**Comment by Vyom-Yadav** [comment]
@rdimitrov Please assign this to me.

**Comment by Vyom-Yadav** [comment]
Thanks for the heads up @rdimitrov! I have not looked at the code of the module where this needs to be fixed,  but I have reproduced the issue locally. See https://gist.github.com/Vyom-Yadav/14cbe386c744c572a9c808e52f5377f6

Shooting in the dark, but this looks like engine + output issue. I was thinking about introducing a `name` field to the rule in a profile:
```yaml
version: v1
type: profile
name: Not-Vyom-github-profile
context:
  provider: github
alert: "on"
remediate: "off"
repository:
  - type: dependabot_configured
    name: "Dependabot Configured for GoLang"  
    def:
      package_ecosystem: gomod
      schedule_interval: daily
      apply_if_file: go.mod
  - type: dependabot_configured
    name: "Dependabot Configured for JS"  
    def:
      package_ecosystem: npm
      schedule_interval: daily
      apply_if_file: docs/package.json
  - type: secret_push_protection
    def:
      enabled: true
      skip_private_repos: true
```
The field would be optional and would introduce a lot of changes (v1alpha1, maybe?). This would change the way we show output. It is very confusing just looking at `dependabot_configured` to tell which one was violated by a repository.

I think this should have been there to begin with as this is a common practice across the policy engines I've worked with. This field would be optional, here is how the engine would compute the name:

1. Using `name` if present.
2. Using just `ruletype` name, if that type is unique in the entity i.e. no two `dependabot_configured`
3. If `ruletype` is not unique, we would add a suffix to `ruletype` name: `ruletype`-(sequential ordering). Sequential ordering would be deterministic as we have a list. This would prevent up from calling a duplicate `...-1` in one place and `...-2` in the other.

Of course, this would require a lot of changes to the engine and how we currently process the rules, but I am up for working on the issue. Wdyt?

**Comment by rdimitrov** [comment]
I was just thinking if it would be helpful to provide an example profile/rule type pair for reproducing this 😃 

In the interest of not breaking the format, what do you think about hashing the rule type def part instead and use this to uniquely differentiate between rules of the same type? Further down you'd also have to take that into account in the way rule evaluations are stored/retrieved - currently it's one entry per rule type (thus the issue).

**Comment by jhrozek** [comment]
> Unique sep. is a predetermined symbol that we won't allow in rule names anymore. 
If the hash is a known size, we wouldn't need to disallow a character from the name, just trim the last N characters + separator from the rule name, the rest would be the name.

**Comment by Vyom-Yadav** [comment]
> If the hash is a known size, we wouldn't need to disallow a character from the name, just trim the last N characters + separator from the rule name, the rest would be the name.

Yes, that would be better. However I have some concerns about just looking at a value and telling a duplicate exists (which was possible using unique sep.), but this can be figured out while implementing the solution. 

@jhrozek @rdimitrov So are we good with introducing a new field? Do you approve of it?

**Comment by rdimitrov** [comment]
@stacklok/minder-maintainers  - what do the rest think about that? Personally I'm leaning towards not introducing a new field for this (unless it's necessary) and instead handle this internally via hashing the rule type data in case of a conflict?

**Comment by Vyom-Yadav** [comment]
Why I think we should have a `name` field, taking gatekeeper as a reference:
- `type: dependabot_configured` -> `ConstraintTemplate`
- Using a rule in a profile -> `Constraint`

```yaml
kind: ConstraintTemplate           
metadata:
  name: k8srequiredlabels
```
```yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: pod-must-have-app-level
```

Both constraint and constraint templates have different names to uniquely identify them. And k8s natively won't support the same kind in the same ns with the same name. We should also do something similar. This is a commonly followed practice in policy engines.
