### ISSUE TITLE
Profile rule_types in docs don't match published rule types

### ISSUE THREAD

**Issue by evankanderson** [stacklok/minder#1798]
### Describe the issue

https://minder-docs.stacklok.dev/how-to/manage_profiles shows a profile with the following rule:

```yaml
- type: branch_protection
        params:
          branch: main
        def:
          required_pull_request_reviews:
            dismiss_stale_reviews: true
            require_code_owner_reviews: true
            required_approving_review_count: 1
          required_linear_history: true
          allow_force_pushes: false
          allow_deletions: false
          allow_fork_syncing: true
```

But we split the `branch_protection` rule type up into a bunch of smaller rules.  (I think this helped composability and partial rollout, but it may have made profiles harder to manage...)

We should either update the docs, or provide a `branch_protection` rule in https://github.com/stacklok/minder-rules-and-profiles/tree/main/rule-types/github
