### ISSUE TITLE
When ingestion fails with an error, don't attempt to remediate

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#1805]
### Describe the issue

I ran into a condition when the ingestor failed hard with an error (which is shouldn't but that's another matter). But from what I can tell, the engine still tried to remediate. I think it shouldn't, an error is not defined state and we shouldn't try to remediate because we can't make a reasonable decision on the ingested entity.

### To Reproduce

There's probably other ways but here's how I stumbled upon the bug:
1. enroll a repo that has no main, only master
2. create a profile with a dependabot rule

The ingestion will fail, but remediation was still attempted according to the profile status:
```
profileStatus:
    lastUpdated: "2023-12-04T10:54:31.758415Z"
    profileId: df9a52ce-86c3-45c5-9d1e-31590ff6baaa
    profileName: black-hat-profile
    profileStatus: error
ruleEvaluationStatus:
    - details: 'error ingesting data: could not clone repo: could not clone repo: couldn''t find remote ref "refs/heads/main"'
      entity: repository
      entityInfo:
        provider: github
        repo_name: pam_hbac
        repo_owner: jhrozek
        repository_id: 66c5e152-6bd9-4a5d-b417-39d883e19892
      guidance: |
        Dependabot enables Automated dependency updates for repositories.
        It is recommended that repositories have some form of automated dependency updates enabled
        to ensure that vulnerabilities are not introduced into the codebase.

        For more information, see
        https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
      lastUpdated: "2023-12-04T10:54:31.758415Z"
      profileId: df9a52ce-86c3-45c5-9d1e-31590ff6baaa
      remediationDetails: 'cannot get ref from: error getting commit ref: GET https://api.github.com/repos/jhrozek/pam_hbac/git/ref/heads/main: 404 Not Found []'
      remediationLastUpdated: "2023-12-04T10:54:31.761939Z"
      remediationStatus: error
      ruleId: 59da5553-71d1-47a5-a174-e80ddcd4e90d
      ruleName: dependabot_configured
      status: error
```
