### ISSUE TITLE
Introduce a new optional name field for rules within a profile

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#2119]
Motivated by the discussions in https://github.com/stacklok/minder/issues/1609#issuecomment-1884847847

The idea is to add an optional name field for when a rule type is being used within a profile. 

**Example:** 
```yaml
version: v1
type: profile
name: Not-Vyom-github-profile
context:
  provider: github
alert: "on"
remediate: "off"
repository:
  - type: dependabot_configured
    name: "Dependabot Configured for GoLang"  
    def:
      package_ecosystem: gomod
      schedule_interval: daily
      apply_if_file: go.mod
  - type: dependabot_configured
    name: "Dependabot Configured for JS"  
    def:
      package_ecosystem: npm
      schedule_interval: daily
      apply_if_file: docs/package.json
  - type: secret_push_protection
    def:
      enabled: true
      skip_private_repos: true
```
