### ISSUE TITLE
Add reasonable defaults to vulncheck evaluator

### ISSUE THREAD

**Issue by JAORMX** [stacklok/minder#2137]
### Please describe the enhancement

The idea is to be able to call the vulncheck evaluator without much configuration, and do the right thing if nothing is passed. That is, add reasonable defaults. Currently, we have to instantiate the `pr_vulnerability_check` rule as follows:

```
pull_request:
  - type: pr_vulnerability_check
    def:
      action: review
      ecosystem_config:
        - name: npm
          vulnerability_database_type: osv
          vulnerability_database_endpoint: https://api.osv.dev/v1/query
          package_repository:
            url: https://registry.npmjs.org/
        - name: go
          vulnerability_database_type: osv
          vulnerability_database_endpoint: https://api.osv.dev/v1/query
          package_repository:
            url: https://proxy.golang.org/
          sum_repository:
            url: https://sum.golang.org/
        - name: pypi
          vulnerability_database_type: osv
          vulnerability_database_endpoint: https://api.osv.dev/v1/query
          package_repository:
            url: https://pypi.org/pypi
```

In the rule definition, this simply calls the `vulncheck` evaluator to do the heavy lifting. Having to add all of this configuration is tedious and error prone.

It would be better if it could just do the right thing.

### Solution Proposal

If no configuration profile configuration is passed, the `vulncheck` evaluator should just use reasonable defaults that can be updated from minder's side.
