### ISSUE TITLE
Shared filesystem between remediator and evaluator corrupts the ingest cache

### ISSUE THREAD

**Issue by Vyom-Yadav** [stacklok/minder#2159]
### Describe the issue

If a profile has remediation turned `on` and data is ingested using `git` and remediation is done using `PRs`, the filesystem is shared between both remediator and evaluator, which corrupts the ingest cache and results in incorrect subsequent rule evaluations. 

### To Reproduce

Reproducing would require two rules, which remediate using `PRs` and ingesting data using `git`. Both the rules should operate on the same file.

To reproduce using the same rules, you would require the fix for #1609 (Check [this](https://github.com/Vyom-Yadav/minder/tree/issue-1609-name-method) proposed fix), which allows two rules of the same name to be evaluated. 

---

- `profile.yaml`
```yaml
version: v1
type: profile
name: Not-Vyom-github-profile
context:
  provider: github
alert: "on"
remediate: "on"
repository:
  - type: dependabot_configured
    def:
      package_ecosystem: gomod
      schedule_interval: daily
      apply_if_file: go.mod  
  - type: dependabot_configured
    name: "DB For NPM"
    def:
      package_ecosystem: npm
      schedule_interval: daily
      apply_if_file: docs/package.json
```

- Register repos in which one repo violates one rule and the other violates both rules.
- Minder would create fixing PRs for both the rules in the repos, which is not expected.,

### What version are you using?

main
