### ISSUE TITLE
Minder doesn't validate the entity for a rule type

### ISSUE THREAD

**Issue by JAORMX** [stacklok/minder#2757]
### Describe the issue

Rule types declare the entity the apply to. Minder is supposed to validate this when creating a profile, but it doesn't.

### To Reproduce

Here's a sample profile:

```yaml
---
version: v1
type: profile
name: test-profile
context:
  provider: github
alert: "on"
remediate: "on"
repository:
  - type: invisible_characters_check
    params: {}
    def: {}
```

Minder is supposed to fail creating this since `invisible_chatacyers_check` applies only to the `pull_request` entity.

Instead, it just creates the profile and then fails when trying to apply policy.

Props to @teodor-yanev on finding this.

### What version are you using?

`main`
