### ISSUE TITLE
Artifact: Ingesting images by digest always returns "latest"

### ISSUE THREAD

**Issue by puerco** [stacklok/minder#3225]
### Describe the issue

When ingesting a container image by digest and no tags are defined, the ingester will skip the specified digest and ingest the last image returned by the the API (generally matching `latest`)

### To Reproduce

This entity should ingest `e3efa96133139eaf23335d6b8aace18c8db9555c026c02d1244ab61af986e181` but instead ingests `4a80bffe07d74bece13c3b954c6463aa25b36492bdfcfc0f674381e0b43f58c9` (`latest` at the time of this report)

```yaml
---
owner: jakubtestorg
name: good-repo-go
type: container
versions: 
  - sha: sha256:e3efa96133139eaf23335d6b8aace18c8db9555c026c02d1244ab61af986e181
  - tags: []
```

### What version are you using?

900bb165611a1b04ab769255ca7f2719fb2b268b
