### ISSUE TITLE
Unhelpful error message on malformed selectors

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#4125]
@eleftherias found two examples:
 - `repository.name = 'test/test'`
 - `repository.isFork == true`

**Comment by jhrozek** [comment]
@eleftherias I tried to reproduce the issue but I couldn't, with a minder instance running locally from main. I tried with these selectors:
```
selection:
  - description: repro
    entity: repository
    selector: repository.name = 'test/test'
```

And I get:
```
Details: selector failed to parse: Syntax error: token recognition error at: '= '
```

For the `isFork` one:
```
selection:
  - description: repro
    entity: repository
    selector: repository.isFork != 'jakubtestorg/bad-go'
```

I get:
```
Details: selector is invalid: undefined field 'isFork'
```

Would you mind showing me how to reproduce better? Did you test with CLI or the UI?
