### ISSUE TITLE
rule types: Validate parameters dict/object

### ISSUE THREAD

**Issue by JAORMX** [stacklok/minder#564]
Currently, Rule types are able to validate rule instantiations via the `rule_schema` key in the definition. Users are also able to create rule types that receive parameters, which can be instantiated in a policy as follows:

```yaml
---
version: v1
type: pipeline-policy
name: acme-github-policy
context:
  ...
repository:
  - context: github
    rules:
      - type: branch_protection
        params:
          branch: main
        def:
          required_pull_request_reviews:
            dismiss_stale_reviews: true
            require_code_owner_reviews: true
            required_approving_review_count: 1
          required_linear_history: true
          allow_force_pushes: false
          allow_deletions: false
          allow_fork_syncing: true
```

This was done via the `params` key in the rule instantiation. We need a mechanism to validate the parameters so users may only introduce appropriate settings there.

# Example

The aforementioned construct for rule definition validation looks as follows:

```yaml
---
version: v1
type: rule-type
name: secret_scanning
context:
  ...
def:
  # Defines the schema for writing a rule with this rule being checked
  rule_schema:
    properties:
      enabled:
        type: boolean
        default: true
  ...
```

So, a rule called in a policy as follows would be valid:

```yaml
version: v1
type: pipeline-policy
name: acme-github-policy
context:
  ...
repository:
  - context: github
    rules:
      - type: secret_scanning
        def:
          enabled: true
```

whereas the following rule would fail validation, and the one wouldn't be able to create it:

```yaml
version: v1
type: pipeline-policy
name: acme-github-policy
context:
  ...
repository:
  - context: github
    rules:
      - type: secret_scanning
        def:
          enabled: "foobar"
```

Rule validation happens on the engine side here: https://github.com/stacklok/mediator/blob/main/internal/engine/rule_types.go#L66-L77

We need a similar construct so we can configure parameter validations in a similar way that rule definition validations.
