### ISSUE TITLE
artifact information should be stored to be referenced in policies

### ISSUE THREAD

**Issue by yrobla** [stacklok/minder#683]
**Describe the bug**
We are currently not storing information of artifacts into the database, so we cannot reference the information in the policy status. So when a policy of type artifact is set, it returns the following info:

```
policyStatus:
    policyId: 1
    policyName: acme-github-policy-artifact
    policyStatus: failure
ruleEvaluationStatus:
    - details: 'evaluation error: data does not match policy: for path .is_signed got <nil>, want true'
      entity: artifact
      entityInfo:
        provider: github
        repo_name: test
        repo_owner: yrobla-org
        repository_id: "1"
      policyId: 1
      ruleId: 1
      ruleName: artifact_signature
      status: failure
      ```
      
  while this is partially true, it misses information about artifact. Entity info in this case reports info about the repo, which is right, but it also misses information about the artifact: name, sha, tag, etc...
We should be storing artifact information into the database, then policy should reference this artifact as entity info, properly displaying the information.
