### ISSUE TITLE
Implement pull request `rule_type`

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#835]
We need a new `rule_type` in order to be checking pull-requests. It could look e.g. like this:
```
---
version: v1
type: rule-type
name: prvulncheck
context:
 provider: github
 group: Root Group
description: Verifies that a PR doesn't propose a vulnerable package.
def:
 # Defines the section of the pipeline the rule will appear in.
 # This will affect the template that is used to render multiple parts
 # of the rule.
 in_entity: pull_request
 # Defines the schema for parameters that will be passed to the rule
 param_schema:
   properties:
     ecosystem:
       "type": array
       "items": {
         "type": "string"
       }
       description: "The package ecosystem to check. The only supported value now is NPM"
 ingest:
   type: pulldepparse
   pulldepparse:
     files:
       - package-lock.json
 eval:
   type: vulncheck
   vulncheck:
     db: osv
     endpoint: https://api.osv.dev/v1/query
```
