### ISSUE TITLE
Write a policy example for verifying dependabot is configured correctly.

### ISSUE THREAD

**Issue by lukehinds** [stacklok/minder#842]
As part of epic stacklok/epics#40 , write a policy example that verifies a certain package eco-system is configured along with an interval

For example

```yml
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
```
